#!/bin/bash

# Check if a folder name was provided
if [ $# -eq 0 ]; then
    echo "❌ No directory name specified."
    exit 1
fi

DIR_NAME=$1

# Create folder and README.md inside it
mkdir -p "$DIR_NAME"
cd "$DIR_NAME"

cat <<EOF > README.md
# $DIR_NAME

This directory and README.md were created automatically via script.
EOF

echo "✅ Directory '$DIR_NAME' and README.md created."

# Move back to repo root
cd ..

# Stage and commit the new folder and README
git add "$DIR_NAME/README.md"
git commit -m "Add $DIR_NAME folder with autogenerated README"
git push origin "$(git rev-parse --abbrev-ref HEAD)"

echo "🚀 Changes pushed to GitHub successfully."
