apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-git-script
spec:
  workspaces:
    - name: source
  steps:
    - name: run-script
      image: ubuntu
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        echo "[INFO] Current directory: $(pwd)"
        echo "[INFO] Listing files:"
        ls -R

        if [ ! -f scripts/myscript.sh ]; then
          echo "[ERROR] scripts/myscript.sh not found!"
          exit 1
        fi

        echo "[INFO] Running the script..."
        chmod +x scripts/myscript.sh
        ./scripts/myscript.sh
