apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: run-script-from-repo-pipelinerun
spec:
  pipelineRef:
    name: run-script-from-repo
  params:
    - name: repo-url
      value: github.com/yash27op/tekton-pipeline
    - name: branch
      value: new
    - name: script-path
      value: scripts/create-pr.sh
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        metadata:
          name: shared-data-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi